require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SurnamesController do

  # This should return the minimal set of attributes required to create a valid
  # Surname. As you add validations to Surname, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurnamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all surnames as @surnames" do
      surname = Surname.create! valid_attributes
      get :index, {}, valid_session
      assigns(:surnames).should eq([surname])
    end
  end

  describe "GET show" do
    it "assigns the requested surname as @surname" do
      surname = Surname.create! valid_attributes
      get :show, {:id => surname.to_param}, valid_session
      assigns(:surname).should eq(surname)
    end
  end

  describe "GET new" do
    it "assigns a new surname as @surname" do
      get :new, {}, valid_session
      assigns(:surname).should be_a_new(Surname)
    end
  end

  describe "GET edit" do
    it "assigns the requested surname as @surname" do
      surname = Surname.create! valid_attributes
      get :edit, {:id => surname.to_param}, valid_session
      assigns(:surname).should eq(surname)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Surname" do
        expect {
          post :create, {:surname => valid_attributes}, valid_session
        }.to change(Surname, :count).by(1)
      end

      it "assigns a newly created surname as @surname" do
        post :create, {:surname => valid_attributes}, valid_session
        assigns(:surname).should be_a(Surname)
        assigns(:surname).should be_persisted
      end

      it "redirects to the created surname" do
        post :create, {:surname => valid_attributes}, valid_session
        response.should redirect_to(Surname.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved surname as @surname" do
        # Trigger the behavior that occurs when invalid params are submitted
        Surname.any_instance.stub(:save).and_return(false)
        post :create, {:surname => { "name" => "invalid value" }}, valid_session
        assigns(:surname).should be_a_new(Surname)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Surname.any_instance.stub(:save).and_return(false)
        post :create, {:surname => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested surname" do
        surname = Surname.create! valid_attributes
        # Assuming there are no other surnames in the database, this
        # specifies that the Surname created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Surname.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => surname.to_param, :surname => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested surname as @surname" do
        surname = Surname.create! valid_attributes
        put :update, {:id => surname.to_param, :surname => valid_attributes}, valid_session
        assigns(:surname).should eq(surname)
      end

      it "redirects to the surname" do
        surname = Surname.create! valid_attributes
        put :update, {:id => surname.to_param, :surname => valid_attributes}, valid_session
        response.should redirect_to(surname)
      end
    end

    describe "with invalid params" do
      it "assigns the surname as @surname" do
        surname = Surname.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Surname.any_instance.stub(:save).and_return(false)
        put :update, {:id => surname.to_param, :surname => { "name" => "invalid value" }}, valid_session
        assigns(:surname).should eq(surname)
      end

      it "re-renders the 'edit' template" do
        surname = Surname.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Surname.any_instance.stub(:save).and_return(false)
        put :update, {:id => surname.to_param, :surname => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested surname" do
      surname = Surname.create! valid_attributes
      expect {
        delete :destroy, {:id => surname.to_param}, valid_session
      }.to change(Surname, :count).by(-1)
    end

    it "redirects to the surnames list" do
      surname = Surname.create! valid_attributes
      delete :destroy, {:id => surname.to_param}, valid_session
      response.should redirect_to(surnames_url)
    end
  end

end
